### ISSUE TITLE
Specify License

### ISSUE THREAD

**Issue by gabrielgio** [buildkite/pipeline-sdk#12]
Nice effort on this SDK! I have been looking for something similar for a while and it is nice to see that is coming from the company itself.

I noticed that the project currently doesn’t specify a license. Would you be able to clarify the licensing for this project? Knowing the license would help me (and others) make sure we're using it correctly.

Thanks.

**Comment by zchase** [comment]
@gabrielgio Thanks for filing an issue! We've updated the license to be MIT. Please keep filing issues if you run into any issues or have any questions, thank you!
