### ISSUE TITLE
Transpile TypeScript SDK to JS 

### ISSUE THREAD

**Issue by zchase** [buildkite/pipeline-sdk#9]

**Comment by wooly** [comment]
Relatedly, it would be super useful to have a sample typescript project that we could use to demo this. I was wrestling yesterday with exports/imports/commonjs/esm nonsense and couldn't get it working so gave up and turned to go.

**Comment by zchase** [comment]
@wooly Ooof sorry about the poor experience. The JS/TS library was as you found not very functional 😂 . [This PR](https://github.com/buildkite/pipeline-sdk/pull/11) should make it much easier and specifically the test suite in there has some very minimal examples. 

I'll get some more practical examples spun up now that there is some testing around SDKs.
